# specify each address explicitly, instead of using "*".
# this ensures responses are sent from the address at which the request was received.
listen_addrs_ipv4 = ["192.168.0.5", "10.0.1.5"]

[[zones]]
# zone: this is the ORIGIN of the zone, aka the base name, '.' is implied on the end
zone = "uninsane.org"

# zone_type: Primary, Secondary, Hint, Forward
zone_type = "Primary"

# file: relative to the `zonedir` option
file = "uninsane.org.zone"

