#! @bash@/bin/sh

# browserpass "validates" the gpg binary by invoking it with --version
if [ "$1" = "--version" ]
then
  echo "sane-browserpass-gpg @version@";
  exit 0
fi

# using exec here forwards our stdin
# browserpass parses the response in
# <browserpass-extension/src/background.js#parseFields>
# it cares about `key:value`, and ignores whatever doesn't fit that (or has an unknown key)
exec @sops@/bin/sops --input-type yaml -d --output-type yaml --config /dev/null /dev/stdin
