#!/usr/bin/env bash
# query the WAN IP address OF MY ROUTER
# requires creds
passwd=$(sudo cat /run/secrets/router_passwd)
cookie=$(mktemp)

# authenticate
curl -s --insecure --cookie-jar $cookie \
  --data "username=admin&password=$passwd" \
  https://192.168.0.1
# query the WAN IP
curl -s --insecure --cookie $cookie \
  -H "X-Requested-With: XMLHttpRequest" \
  "https://192.168.0.1/cgi/cgi_action?Action=GetConnectionStatus" \
  | jq -r .wan_status.ipaddr
