#!/usr/bin/env bash
set -ex

mnt=/mnt/servo-media-wan
# if lan not mounted, then try to mount it
if ! (test -d /mnt/servo-media-lan/Music)
then
  sudo mount /mnt/servo-media-lan && mnt=/mnt/servo-media-lan
fi

# if the needed mount isn't mounted, mount it
if ! (test -d $mnt/Music)
then
  sudo mount $mnt
fi

# symlink the fastest mount point into place
# uncomment if i see the bug again: sudo unlink /mnt/servo-media  # XXX ln gets confused if the destination is a symlink to a stale mount
sudo ln -sf $mnt /mnt/servo-media
